language: bash

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential zlibc make autoconf libtool picolisp

before_script:
  - wget http://software-lab.de/picoLisp-3.1.9.tgz -O /tmp/picolisp.tgz
  - cd /tmp; tar -xf /tmp/picolisp.tgz
  - cd /tmp/picoLisp/src64 && make

script:
  - cd ${TRAVIS_BUILD_DIR} && /tmp/picoLisp/pil test.l
